### ISSUE TITLE
Agreement holders should be able to discard minor amendments

### ISSUE THREAD

**Issue by calebissharp** [bcgov/range-web#606]
The plan should be reverted to the most recent approved version.

Currently, the plan is to completely remove all changes introduced by a discarded amendment.

Related to #471

**Comment by LisaMoore1** [comment]
Cancel option in the discard amendment workflow doesn’t do anything (doesn’t exit out of the workflow)

**Comment by LisaMoore1** [comment]
@calebissharp Wondering if there is something up with the merge here. 

- cancel button still not working
- selecting discard generates a blank red error message at the top right (is that called a toast?) and the discard doesn’t happen

**Comment by calebissharp** [comment]
@LisaMoore1 Yep, both of those things should have been fixed and deployed to test.

**Comment by LisaMoore1** [comment]
I’m in a holding pattern on this one until I know I should try to test again.

**Comment by ZoeSimon** [comment]
@micheal-w-wells says "I added some temp placeholder text to prove deployments and merges are working. Note that even after clearing cache I didn't see the new changes! I had to make sure all my myrange tabs were closed and then clear cache in order for it to work"

![Clipboard - March 27, 2020 4_20 PM](https://user-images.githubusercontent.com/62561887/77808417-70c2eb00-7048-11ea-8ed5-81c8d21c4d5c.png)

@LisaMoore1 @calebissharp

**Comment by calebissharp** [comment]
@LisaMoore1 Since that other issue was fixed by clearing cache, this one can probably be looked at again.

**Comment by LisaMoore1** [comment]
I think if a version is discarded it should either be removed from the version list or identified as having been discarded (no action needed until we actually look at this issue again — I just bumped into it while doing something else and didn’t want to forget).

**Comment by LisaMoore1** [comment]
Similar to #760. Version list is still showing the discarded version however WQ/status seemed to behave as expected in the case I tested (RAN099954).
