### ISSUE TITLE
Bare bones DM

### ISSUE THREAD

**Issue by micheal-w-wells** [bcgov/range-web#855]
- [x] Can see RUP(s)
- [x] Can see recommendation/attachments
- [ ] Help text to be determined during UI dev of file attachments 
- [x] Can capture decision by moving buttons over to DM from staff
- [ ] Add conditions text area that only they can edit to the RUP.  @LisaMoore1 to write description/help text

**Comment by LisaMoore1** [comment]
I think this is related to web #865 and #877.

**Comment by LisaMoore1** [comment]
DM unable to view attachments sent to visible to all staff. 
![D795241D-7A6C-4014-BA7A-67621CB6550C.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/e78ebea1-dc95-4cb5-853c-a30084365550)

DM unable to edit the conditions field (note that staff also unable to edit their field during any status that I can find)
![90BD5FB8-6835-43F4-B3AC-7AE1B4E37A10.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/c1250230-0031-4911-989e-79a97a28bb8e)

**Comment by calebissharp** [comment]
@LisaMoore1 Both of these issues should be fixed now.

**Comment by LisaMoore1** [comment]
Attachments good but DM still not able to edit the conditions field.  I’ll make another issue to indicate that staff are also unable to edit the conditions field in any status.

**Comment by LisaMoore1** [comment]
@calebissharp Curious how much work/effort it would be to give the DMs the same screen AHs get when they submit for decision (the one that requires them to select the checkbox before OK to officially sign) rather than just a change status message box?  I’m worried there may be legal implications of not notifying DMs they are making a legally binding signature when they “change status”.

**Comment by calebissharp** [comment]
@LisaMoore1 Hmm, I'm not sure. I don't think it would be simple though. 

Can prioritize if this is a legal requirement though.

**Comment by LisaMoore1** [comment]
@calebissharp Let’s leave the signature screen for now (I’m making a note of this issue number so I can find it again if needed). Closing this because the other elements are resolved.  Thanks!

**Comment by calebissharp** [comment]
That works for me!
