### ISSUE TITLE
Amend from Legal after WMWE is not working

### ISSUE THREAD

**Issue by LisaMoore1** [bcgov/range-web#907]
RAN099941 Version 21 is a minor amendment that I push through to review and then DM sets as WMWE. 
The WQ shows a "Wrongly Made Without Effect" version (top most) 
![5C837568-04EA-4EA4-B3E2-D2FC7367BE94.jpeg](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/e2f39e88-31e7-42c2-ad3c-ddaf180e1be2)

I open that one then...after selecting "Amend from legal", the  popup stays open with these errors
![AmendFromLegal1.JPG](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/f04d2c5b-e415-463f-97f1-3edec5812888)

Returning to the WQ the "AH Minor - WMWE" row is now in the versions and says "approved" and new "approved" version becomes most recent (at least I think that's what's happening). Note that the "Initial RUP" version is also showing "approved"
![WMWE work queu switched to APPROVED version.JPG](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/13048ea8-f9b3-44ea-8d06-f3aa65da746c)

**Comment by LisaMoore1** [comment]
@calebissharp — any ideas what might be happening here? It goes back to all of the versioning stuff.  The things that are bothering me with this are: 
- the amend from legal staying up on the screen (I eventually hit cancel to get back to the WQ)
- the “AH Minor - WMWE” showing up as Approved
- I cannot find a way to look at the actual amendment that was WMWE (ex. for RAN099941 v21) from the WQ (I need to be able to see what wasn’t accepted somehow)

@mike-w-wells any possibility the WQ stuff is the same as #800? I’m having a hard time knowing describing what I’m observing without being sure I’m not straying from one issue into a different one. Sorry about that.

**Comment by calebissharp** [comment]
I can reproduce this locally. Seems like the `/restore` endpoint is throwing an error. 

The error for reference: 
```
insert into "plan_file" ("access", "id", "name", "plan_id", "type", "url", "user_id") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - duplicate key value violates unique constraint "plan_file_pkey
```

Something to do with files.

**Comment by calebissharp** [comment]
Should be good to test once the above PR deploys.

**Comment by LisaMoore1** [comment]
@calebissharp @micheal-w-wells. The nearest I can figure there is a difference between amend from legal if the WMWE started from a plan in APPROVED status versus starting from a STANDS status:


From STANDS what is happening (it seems) is: 
1. AH makes original minor amendment — shows as “stands” (SNR) because it hasn’t yet been reviewed —> expected
2. Staff switches it to requires review — status is updated and now DM can take action —> expected
3. DM updated to WMWE —> expected except DM should not be able to add conditions here (I’ll make separate issue for that)
4. AH WQ now shows “not accepted” in very top row (before expand versions) —> expected I think
5. AH WQ now shows “stands” on the AH Minor - WMWE row in versions — really confusing because how can something be WMWE AND “stands”? None of the versions in the list show the amended version with the content that was deemed WMWE —> we clearly need to see which version was WMWE and what the content of that was
6. AH attempts “Amend from Legal” — popup comes but stays up even after confirmed...have to “cancel” to close it —> unexpected
7. AH WQ now shows top row as SNR — I’m really not sure what the difference between top row not expanded and top row expanded is but I know after a minor amendment has been set to WMWE we don’t want to return to a SNR status because it WAS reviewed and determined to be WMWE. The current legal should be the last version that was either approved or stands (having either been reviewed and allowed to stand or determined not to need a review and stands)
8. A couple of extra versions get added to the list (showing as stands) I think from passing back and forth between staff and DM. Those versions aren’t really relevant to users. What a user needs is:
   - what was approved
   - what was submitted as amendment (that was deemed WM or WMWE)
   - what is the current legal version

From approved the amend from legal option is working but the version list is still confusing (see above).

**Comment by calebissharp** [comment]
> AH attempts “Amend from Legal” — popup comes but stays up even after confirmed...have to “cancel” to close it —> unexpected

I can't reproduce this. Something is throwing an error, but I can't get it locally anymore after https://github.com/bcgov/range-api/pull/250 was merged. If you could tell me what RAN you're getting this on that would be great.

**Comment by LisaMoore1** [comment]
@calebissharp RAN099951 I think.

**Comment by calebissharp** [comment]
@LisaMoore1 Can you try again with the devtools open to catch any errors? Also if you do see an error, can you expand it with the little arrow so we can see the actual error message?

**Comment by calebissharp** [comment]
@LisaMoore1 Can you try once more? We merged in a PR that changes the structure of `ref_client` and it's possible the snapshot that was trying to be restored was from before that PR was merged, causing the restore endpoint to error.

**Comment by LisaMoore1** [comment]
@calebissharp still getting erros.

![WMWE work queu switched to APPROVED version.JPG](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/68db626b-df85-40f3-baf3-cd6aa3d210a0)

**Comment by LisaMoore1** [comment]
@calebissharp still getting errors![AmendFromLegal_DevTools(3WMWE).JPG](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/34925842-607d-4fb7-8f5d-62895c766f72)

**Comment by calebissharp** [comment]
Can you expand the little arrow beside the bottom error please?

**Comment by LisaMoore1** [comment]
![AmendFromLegal_DevTools(3WMWE)2.JPG](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/baa46e54-4d40-437d-9027-760c2f8570fa)

**Comment by calebissharp** [comment]
@LisaMoore1 Thanks. Can you also expand the arrow beside `data`? I can only see part of the error message right now.

**Comment by calebissharp** [comment]
Can you get this error with a completely new RUP? If so, I think there's a problem with the API deploy. @micheal-w-wells Has that OpenShift upgrade happened yet?

**Comment by LisaMoore1** [comment]
Looked like it was still cutting some stuff off so trying two separate images. 
![AmendFromLegal_DevTools(3WMWE)3-expand.JPG](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/396e5a64-be6d-436b-94f0-cf1a4f041902)

![AmendFromLegal_DevTools(3WMWE)3-hover.JPG](https://images.zenhubusercontent.com/5d937161c8e4d80001227881/b723bd60-7e2d-49f7-8bc9-b1c054c21721)

**Comment by LisaMoore1** [comment]
Just did another full work through these on a fresh RUP and not getting any errors.  Shall I close and keep testing other stuff in the amendment workflow and reopen if it happens again?

**Comment by calebissharp** [comment]
@LisaMoore1 I think so, yep. The original error in this issue was fixed, this other one you're getting is an artifact of the data in test I'm fairly certain.
